name: CI

on: [push]

jobs:

  macOS:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Tests
        run: swift test --parallel

  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v4

      - name: Tests
        run: swift test --parallel
