name: CI

on: [push]

jobs:

  macOS:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: swift build

      - name: Tests
        run: swift test --skip-build --disable-xctest --parallel
