name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      
      - uses: actions/checkout@v4

      - name: Build
        run: swift build

      - name: Tests
        run: swift test --skip-build --parallel
